---
- name: instal mariadb
  yum:
    name: "{{item}}"
    state: present
  become: yes
  become_user: "{{ansible_become_user}}"
  become_method: "{{ansible_become_method}}"
  with_items:
    - mariadb-server
    - mariadb

- name: enable the mariadb service
  service:
    name: mariadb
    enabled: yes
- name: start the mariadb service
  service:
    name: mariadb
    state: started
- name: create the mysql user
  mysql_user:
    name: "{{mariadb_scm_user}}"
    password: "{{mariadb_scm_password}}"
    priv: '*.*:ALL,GRANT'
    state: present
- name: Create a new database with name 'bobdata'
  mysql_db:
    name: "{{cloudera_scm_db}}"
    state: present

- name: Open up FirewallD for ldap 
  command: "firewall-cmd --zone=dmz --add-port={{item}}/tcp --permanent"
  with_items:
    - 3306
- name: reload firewalld
  command: firewall-cmd --reload