---
# tasks file for common

- name: enable epel-release repo (or need to pull python-pip to local repo)
  yum:
    name: epel-release
    state: present
  become: yes
  become_user: "{{ansible_become_user}}"
  become_method: "{{ansible_become_method}}"

# - name: ensure core packages are installed
#   yum:
#     name: "{{item}}"
#     state: present
#   become: yes
#   become_user: "{{ansible_become_user}}"
#   become_method: "{{ansible_become_method}}"
#   with_items: "{{common_yum_packages}}"

- name: ensure core packages are installed
  yum:
    name: "{{common_yum_packages}}"
    state: present
  become: yes
  become_user: "{{ansible_become_user}}"
  become_method: "{{ansible_become_method}}"

- name: Add Cloudera repo
  template:
    src: cloudera-manager.repo.j2
    dest: "/etc/yum.repos.d/cloudera-manager{{cdh_version}}.repo"

- name: install cloudera packages
  yum:
    name: "{{item}}"
    state: present
  become: yes
  become_user: "{{ansible_become_user}}"
  become_method: "{{ansible_become_method}}"
  with_items:
    - cloudera-manager-agent.x86_64
    - cloudera-manager-daemons.x86_64

- name: Disable transparent huge page - defrag
  shell: echo "never" > /sys/kernel/mm/transparent_hugepage/defrag
 
- name: Disable transparent huge page - enabled
  shell: echo "never" > /sys/kernel/mm/transparent_hugepage/enabled
 
- name: VM swappiness - 1
  shell: echo "1" > /proc/sys/vm/swappiness
 
- name: Set VM swappiness - 2
  sysctl:
    name: vm.swappiness
    value: 1
    state: present

- name: allow ntp through firewall
  shell: firewall-cmd --add-service=ntp --permanent
  when: inventory_hostname in groups['scm']


- name: firewall reload
  shell: firewall-cmd --reload
  when: inventory_hostname in groups['scm']


- name: Make sure Chrony is started up
  service: name=chronyd state=running enabled=yes
  tags: chrony
  when: inventory_hostname in groups['scm']

- name: set timezone
  shell: timedatectl set-timezone Asia/Singapore

- name: Install NTP
  yum: name=ntp state=installed 
  tags: ntp

- name: Copy over the NTP configuration
  template:
    src: ntp.conf.j2
    dest: /etc/ntp.conf
  notify:
  - restart ntpd
  tags: ntp

- name: Make sure NTP is stopped
  service: name=ntpd state=stopped enabled=yes
  tags: ntp

- name: Sync time initialy
  shell: ntpdate {{hostvars[groups['scm'][0]]['inventory_hostname']}}
  tags: ntp

- name: Make sure NTP is started up
  service: name=ntpd state=running enabled=yes
  tags: ntp

- name: Sync hwclock
  shell: hwclock -w
  tags: ntp