---
# tasks file for common

- name: enable epel-release repo (or need to pull python-pip to local repo)
  yum:
    name: epel-release
    state: present
  become: yes
  become_user: "{{ansible_become_user}}"
  become_method: "{{ansible_become_method}}"

# - name: ensure core packages are installed
#   yum:
#     name: "{{item}}"
#     state: present
#   become: yes
#   become_user: "{{ansible_become_user}}"
#   become_method: "{{ansible_become_method}}"
#   with_items: "{{common_yum_packages}}"

- name: ensure core packages are installed
  yum:
    name: "{{common_yum_packages}}"
    state: present
  become: yes
  become_user: "{{ansible_become_user}}"
  become_method: "{{ansible_become_method}}"

- name: Add Cloudera repo
  template:
    src: cloudera-manager.repo.j2
    dest: "/etc/yum.repos.d/cloudera-manager{{cdh_version}}.repo"


- name: allow ntp through firewall
  shell: firewall-cmd --add-service=ntp --permanent
  when: inventory_hostname in groups['scm']


- name: firewall reload
  shell: firewall-cmd --reload
  when: inventory_hostname in groups['scm']


- name: Make sure Chrony is started up
  service: name=chronyd state=running enabled=yes
  tags: chrony
  when: inventory_hostname in groups['scm']

- name: set timezone
  shell: timedatectl set-timezone Asia/Singapore

- name: Install NTP
  yum: name=ntp state=installed 
  tags: ntp

- name: Copy over the NTP configuration
  template:
    src: ntp.conf.j2
    dest: /etc/ntp.conf
  notify:
  - restart ntpd
  tags: ntp

- name: Make sure NTP is stopped
  service: name=ntpd state=stopped enabled=yes
  tags: ntp

- name: Sync time initialy
  shell: ntpdate 172.16.20.1
  tags: ntp

- name: Make sure NTP is started up
  service: name=ntpd state=running enabled=yes
  tags: ntp

- name: Sync hwclock
  shell: hwclock -w
  tags: ntp