---
- name: install passlib
  pip:
    name:
      - passlib
    state: present
- name: generate a random password
  set_fact:
    RANDOM_PASSWD: "{{ansible_date_time.iso8601_basic}}"
#    RANDOM_PASSWD_CRYPT: "{{ inventory_hostname | password_hash('sha512') | password_hash('sha512') }}"

- name: display the password in build. Note it carefully. (Not in Prod. We must lodge it into Vault)
  debug:
    var: RANDOM_PASSWD

- name: "Set the password for {{item}}"
  user:
    name: "{{item}}"
    password: "{{RANDOM_PASSWD}}"