---
# - name: include rpm tasks
#   include_tasks: local_bin_install_cm.yml
#   tags:
#     - local_bin_install_cm

# - name: scm prepare database
#   shell: /usr/share/cmf/schema/scm_prepare_database.sh mysql -h {{db_private_ip}} -u{{mariadb_scm_user}} -p{{mariadb_scm_password}} --scm-host {{groups['scm'][0]}} scm scm scm JAVA_HOME=/usr/java/jdk1.7.0_67-cloudera/


- name: include rpm tasks
  include_tasks: rpm_install_cm.yml
  tags:
    - rpm_install_cm

- name: Open up FirewallD for scm 
  command: "firewall-cmd --zone=dmz --add-port={{item}}/tcp --permanent"
  with_items:
    - "{{cloudera_ports}}"
    - "{{cdh_services_ports}}"
    - "{{cdh_third_party_ports}}"
- name: reload firewalld
  command: firewall-cmd --reload