---
# defaults file for ldap
root_dns_hosted_zone: amitthk.com
ldap_server_domain_name: ldap.amitthk.com
ldap_server_rootpw: changethis
ldap_server_enable_ssl: false
ldap_root_dn_suffix: "dc={{ ldap_server_domain_name.split('.')[0] }},dc={{ ldap_server_domain_name.split('.')[1] }},dc={{ ldap_server_domain_name.split('.')[2] }}"
ldap_password_hash_type: "{SSHA}"
ldap_host_ip: "{{groups['ldap'][0]}}"
AWS_ACCESS_KEY_ID: ""
AWS_SECRET_ACCESS_KEY: ""

env:
 RUNLEVEL: 1
ldap_server_pkgs:
  - openldap-servers
  - openldap-clients
  - libselinux-python
  - openssl

ldap_server_app_path: "/etc/openldap/"
ldap_server_user: ldapadmin
ldap_server_admin: "{{ldap_server_user}}"