---
- name: Prerequisites
  become: true
  gather_facts: False
  hosts: all
  roles:
    - common

- name: db
  hosts: db
  roles:
    - db

- name: ldap
  hosts: ldap
  roles:
    - ldap

- name: kerberos
  hosts: kerberos
  roles:
    - kerberos

- name: SCM
  hosts: scm
  roles:
    - cdh-scm

- name: master
  hosts: masters
  roles:
    - cdh-master

- name: worker
  hosts: workers
  roles:
    - cdh-worker

- name: gateway
  hosts: gateways
  roles:
    - cdh-gateway