---
- name: Basic
  become: true
  gather_facts: True
  hosts: all
  become: no
  become_user: "{{ansible_become_user}}"
  become_method: "{{ansible_become_method}}"
  tasks:
    - name: ping the host
      ping:
    - copy:
        content: "{{hostvars | to_nice_json}}"
        dest: "{{inventory_dir}}/hostvars.json"
      delegate_to: localhost
    - debug: 
        msg: "{{hostvars[groups['scm'][0]]['inventory_hostname']}}"
    - debug: 
        msg: "{{hostvars[inventory_hostname]['ansible_default_ipv4']['address']}}"
    - debug: 
        msg: "{{hostvars[groups['scm'][0]]['ansible_default_ipv4']['address']}}"
  tags:
    - ping