---
- name: Basic
  become: true
  gather_facts: True
  hosts: all
  become: no
  become_method: sudo
  tasks:
    - name: ping the host
      ping:
    - copy:
        content: "{{hostvars | to_nice_json}}"
        dest: "{{inventory_dir}}/hostvars.json"
      delegate_to: localhost
    - debug: 
        msg: "{{hostvars[groups['scm'][0]]['inventory_hostname']}}"
    - debug: 
        msg: "{{hostvars[inventory_hostname]['ansible_default_ipv4']['address']}}"
    - debug: 
        msg: "{{hostvars[groups['scm'][0]]['ansible_default_ipv4']['address']}}"
    - name: create /tmp
      file:
        path: /tmp
        state: directory
        mode: '0777'
      become: yes
      become_method: sudo
  tags:
    - ping
